name: workshop
channels:
  - conda-forge
dependencies:
  - python==3.7.9
  - fire==0.4.0
  - jupyterlab==3.2.0
  - dvc==2.8.1
  - opencv==4.1.0
  - pillow==8.2.0
  - pandas==1.3.3
  - kedro==0.17.5
  - mlflow==1.20.2
  - scikit-learn==0.24.1
  - pandas-profiling==3.1.0
  - jupyter_contrib_nbextensions==0.5.1
