name: workshop
channels:
  - conda-forge
dependencies:
  - python==3.7.12
  - fire==0.4.0
  - jupyterlab==3.2.4
  - pillow==8.2.0
  - pandas==1.3.4
  - kedro==0.17.5
  - mlflow==1.22.0
  - scikit-learn==1.0.1
  - pandas-profiling==3.1.0
  - jupyter_contrib_nbextensions==0.5.1
  - opencv=4.5.3
  - pip==21.3.1
  - pip:
    - dvc==2.8.3
