name: workshop
channels:
  - conda-forge
dependencies:
  - python==3.7.9
  - fire==0.2.1
  - jupyterlab==2.2.8
  - dvc==1.7.2
  - opencv==4.1.0
  - pillow==7.2.0
  - pandas==1.1.2
  - kedro==0.16.5
  - mlflow==1.11.0
  - scikit-learn==0.23.2
  - pandas-profiling==2.9.0