[project]
name = "workshop"
version = "24.12.05"
description = "Baseimage used in the workshop 'from jupyter to production'"
requires-python = ">=3.11, <3.13"
dependencies = [
    "jupyterlab>=4,<5",
    "jupyterlab-code-formatter>=3,<4",
    "jupyterlab-lsp>=5,<6",
    "pandas>=2",
    "scikit-learn>=1.5",
]

[dependency-groups]
dvc = ["dvc>=3.22", "pathspec<1.0.0"]
dagster = [
    "dagster>=1.8.0,<1.9.3",
    "dagster-mlflow>=0.24.0,<0.26",
    "dagster-postgres>=0.24.0,<0.26",
    "dagster-webserver>=1.8.0,<1.9.3",
    "jupytext>=1.15.2,<2",
    "xgboost>=3.0,<4",
]
mlflow = [
    "mlflow[extras]>=2.7",
    "psycopg2-binary>=2.9.10,<3",
    "pymysql[rsa]>=1.1.1,<2",
]
onnx = [
    "fastapi[standard]>=0.115.6,<0.116",
    "onnxruntime>=1.20,<2",
    "skl2onnx>=1.17.0,<2",
]
dev = [
    "pre-commit>=4.0,<5",
    "black>=25,<26",
]
